LEVEL_INTRO = hash("level_intro")
LEVEL_GAME = hash("level_game")

function init(self)
	self.level = LEVEL_INTRO
	msg.post(".", "acquire_input_focus")
	msg.post("#intro", "load")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("start_game") then
		msg.post("#intro", "unload")
		msg.post("#main", "load")
	end
	
	if message_id == hash("proxy_loaded") then
		msg.post(sender, "init")
		msg.post(sender, "enable")
	end
end